### ISSUE TITLE
Driver throws exception when using with python

### ISSUE THREAD

**Issue by mballav** [wise-coders/salesforce-jdbc-driver#5]
I have successfully integrated CData's JDBC driver for Salesforce into my python code. I tried to do the same with DbSchema's JDBC driver, but did not succeed. When I create a connection, it throws the following exception:

```Data is = username=manish.ballav@syntelli.com;password=<passwordWithToken>
Traceback (most recent call last):
  File "org.jpype.JPypeContext.java", line -1, in org.jpype.JPypeContext.callMethod
  File "Method.java", line 498, in java.lang.reflect.Method.invoke
  File "DelegatingMethodAccessorImpl.java", line 43, in sun.reflect.DelegatingMethodAccessorImpl.invoke
  File "NativeMethodAccessorImpl.java", line 62, in sun.reflect.NativeMethodAccessorImpl.invoke
  File "NativeMethodAccessorImpl.java", line -2, in sun.reflect.NativeMethodAccessorImpl.invoke0
  File "DriverManager.java", line 270, in java.sql.DriverManager.getConnection
  File "DriverManager.java", line 664, in java.sql.DriverManager.getConnection
  File "SalesforceJdbcDriver.java", line 81, in com.dbschema.salesforce.SalesforceJdbcDriver.connect
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/jaydebeapi/__init__.py", line 412, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/jaydebeapi/__init__.py", line 230, in _jdbc_connect_jpype
    return jpype.java.sql.DriverManager.getConnection(url, *dargs)
java.sql.SQLException: java.sql.SQLException: Missing username. Please add it to URL as user=<value>
```

**Comment by wise-coders** [comment]
Please check the last line from the exception:  Missing username. Please add it to URL as user=<value>
The issue is related to the URL.

Best regards,
 Dragos Pruteanu

**Comment by mballav** [comment]
Thanks Dragos. The problem indeed was with the URL, but the source of error was misleading documentation (README.rst) on your github page.

First when I used the URL indicated in your docs, it did not work: jdbc:dbschema:saleforce://username=lulu@yahoo.com;password=somepasswordwithtoken

Then, I used the URL indicated on CData's website:
jdbc:salesforce:User=<username>;Password=<token>;Security Token=<token>

And, that worked!

Could you kindly update your documentation?

Regards,
Manish

**Comment by wise-coders** [comment]
I checked now, and I think your application is picking the CData JDBC driver up.

[1] https://www.cdata.com/kb/tech/salesforce-jdbc-tomcat.rst

Our driver is using the class

com.dbschema.salesforce.SalesforceJdbcDriver

with this URLs:

<driver cls="com.dbschema.salesforce.SalesforceJdbcDriver" url="jdbc:dbschema:salesforce://" description="DbSchema Driver" website="[2] https://dbschema.com"/>
        <driver cls="com.dbschema.salesforce.SalesforceJdbcDriver" url="jdbc:dbschema:salesforce://sessionid={PARAM}" authenticate="true" param="SessionId" description="DbSchema Driver use SessionId" website="[3] https://dbschema.com"/>
        <driver cls="com.dbschema.salesforce.SalesforceJdbcDriver" url="jdbc:dbschema:salesforce://tables=custom" description="DbSchema Driver, Custom Tables" website="[4] https://dbschema.com"/>
        <driver cls="com.dbschema.salesforce.SalesforceJdbcDriver" url="jdbc:dbschema:salesforce://sessionid={PARAM}&amp;tables=custom" authenticate="true" param="SessionId" description="DbSchema Driver use SessionId, Custom Tables" website="[5] https://dbschema.com"/>

Best regards,
 Dragos Pruteanu

[1] https://www.cdata.com/kb/tech/salesforce-jdbc-tomcat.rst
[2] https://dbschema.com%22/
[3] https://dbschema.com%22/
[4] https://dbschema.com%22/
[5] https://dbschema.com%22/

**Comment by mballav** [comment]
Dragos:

You are correct. It was indeed picking up CData's JDBC driver.

With DbSchema's driver, I continue to get the same exception even though I have tried the following variations of the URL:

jdbc:dbschema:salesforce://username=<email>;password=<passwordWithSecurityToken>
jdbc:dbschema:salesforce://user=<email>;password=<passwordWithSecurityToken>
jdbc:dbschema:salesforce://User=<email>;Password=<passwordWithSecurityToken>

Please help.

**Comment by mballav** [comment]
At last, I could make it work, but I had to study the code. The issue was with the user and password separator. The correct version of the URL is:

jdbcapi+sfjdbc://jdbc:dbschema:salesforce://user=<email>&password=<passwordWithToken>

Please note the "&" and not ";" as the separator. README has Java code sample that uses a semi-colon, not ampersand.

**Comment by wise-coders** [comment]
Thank you, you are right. We fixed the documentation as you suggested.

**Comment by jon-tresko** [comment]
Is it possible to use a custom mydomain?

**Comment by wise-coders** [comment]
This is the class we use to connect: 
https://github.com/forcedotcom/wsc/blob/master/src/main/java/com/sforce/ws/ConnectorConfig.java

Do you know which one should be the domain?
