### ISSUE TITLE
Driver errors on Java 11 method?

### ISSUE THREAD

**Issue by jrbocarsly** [wise-coders/salesforce-jdbc-driver#6]
Hi
In trialing this driver (using dbschema-salesforce-jdbc1.2.jar; mod date August ‎03, ‎2021, ‏‎8:42:12 AM) , running adoptium jdk 8u292-b10, we got NoSuchMethodError on String.isBlank() (see below), which we found interesting because that method is a Java 11 method even though the class version is 52.

Thanks for your attention to this.
Regards
J Bocarsly

url=jdbc:dbschema:salesforce://tables=all
Data is = tables=all
key=tables val=all
Aug 13, 2021 9:45:44 AM com.dbschema.salesforce.SalesforceJdbcDriver getSalesforceConnection
INFO: Create H2 database 'jdbc:h2:file:/C:/Users/jbocarsly/.DbSchema/jdbc-salesforce-cache/d58bd64eaf4f49a79dd611cc87d684e3;database_to_upper=false'
Aug 13, 2021 9:45:44 AM com.dbschema.salesforce.SalesforceJdbcDriver getSalesforceConnection
INFO: Create H2 database 'jdbc:h2:file:/C:/Users/jbocarsly/.DbSchema/jdbc-salesforce-cache/d58bd64eaf4f49a79dd611cc87d684e3;database_to_upper=false'
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.String.**isBlank**()Z
	at com.dbschema.salesforce.SalesforceConnection.transferDataForTablesFromQuery(SalesforceConnection.java:70)
	at com.dbschema.salesforce.SalesforceConnection.access$300(SalesforceConnection.java:29)
	at com.dbschema.salesforce.SalesforceConnection$StatementProxy.invoke(SalesforceConnection.java:126)
	at com.sun.proxy.$Proxy0.executeQuery(Unknown Source)
	at com.rttsweb.util.SimpleDAO.sqlQuery(SimpleDAO.java:95)
	at com.rttsweb.workspace.Workspace_SFDC_dbschema_driver.main(Workspace_SFDC_dbschema_driver.java:54)

**Comment by wise-coders** [comment]
We fixed this right now. A new driver is deployed on the website, under the same version. Please check.

**Comment by jrbocarsly** [comment]
It behaves as espected. Thanks for the quick response.
